### ISSUE TITLE
Bootnotification with status pending are not handled correctly

### ISSUE THREAD

**Issue by bbouisson** [jerome-benoit/charging-stations-simulator#124] opened 2021-12-16 16:53 UTC
When the CPO server is sending back a bootnotification with status pending, the simulator should not send new commands except for new bootnotifications.
Today it still sends status notification (cf screenshot)
![bootnotif_pending_issue](https://user-images.githubusercontent.com/26277793/146414462-23d309ac-0453-4c05-9e63-8880db96c242.png)

**Comment by jerome-benoit** [comment] 2021-12-20 16:03
I cannot reproduce either by returning nothing to the simulator (hang forever, it's a bug simulator side but unrelated) or REJECTED. 
The loop that retry BootNotification in case not ACCEPTED is returned just works as expected if anything else then ACCEPTED is returned to a BootNotification. 

Be sure: 
+ to use the latest version; 
+ to use node.js latest LTS version (16.x.x);
+ to have autoRegister set to false in the used CS template. 

Please join in any case the configuration file and the CS template you use when filling a bug report.

**Comment by jerome-benoit** [comment] 2022-02-08 10:20
Since we cannot reproduce and no further informations were given, I close the issue.

**Closed by jerome-benoit** 2022-02-08 10:20 UTC
